linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errorlint
    - gci
    - gocritic
    - godot
    - goimports
    - misspell
    - perfsprint
    - typecheck
    - whitespace
    - wrapcheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/release-argus/Argus)
  goimports:
    local-prefixes: github.com/release-argus/Argus
  perfsprint:
    # Optimises into `err.Error()` even if it is only equivalent for non-nil errors.
    err-error: true