version: "2"
linters:
  enable:
    - dupl
    - dupword
    - durationcheck
    - errorlint
    - gocritic
    - godot
    - misspell
    - perfsprint
    - unconvert
    - usestdlibvars
    - whitespace
    - wrapcheck
  settings:
    perfsprint:
      err-error: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/release-argus/Argus)
    goimports:
      local-prefixes:
        - github.com/release-argus/Argus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
