export { Defaults as AccountDefaultsPage } from './account/defaults';
export { SettingsLayout } from './account/layout';
export { Account as AccountPage } from './account/profile';
export { Tokens as TokensPage } from './account/tokens';
export { Groups as GroupsPage } from './admin/groups';
export { Users as UsersPage } from './admin/users';
export { Approvals as ApprovalsPage } from './approvals';
export { Login as LoginPage } from './login';
export { Flags as FlagsPage } from './status/cli_flags';
export { Config as ConfigPage } from './status/configuration';
export { Status as StatusPage } from './status/runtime_and_build_info';
